### ISSUE TITLE
Delete Repo?

### ISSUE THREAD

**Issue by michaelsilver** [246overclocked/OverclockedLibrary#1]
Since we have converted to using a different overclocked library for each project, tracked in the repo with the rest of the source code of that project, I don't think a separate OverclockedLibary repo is necessary anymore.

I looked through the history and there is nothing important -- only old versions of Vector2D and Potentiometer. 

Should we delete it given that's just an empty repo now?

**Comment by PaulTerrasi** [comment]
@MichaelSilver That sounds fine to me.

**Comment by michaelsilver** [comment]
OK, deleting.
